#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Vin.ly.Resource", IsApplication=true)]

namespace Vin.ly
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070029
			public const int AddButton = 2131165225;
			
			// aapt resource value: 0x7f070031
			public const int AddText = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int AddUserName = 2131165235;
			
			// aapt resource value: 0x7f07000e
			public const int AddWineComment = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int AddWineName = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int AddWineRegion = 2131165196;
			
			// aapt resource value: 0x7f07002e
			public const int AddWineTexter = 2131165230;
			
			// aapt resource value: 0x7f07000a
			public const int AddWineType = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int Clear = 2131165217;
			
			// aapt resource value: 0x7f070030
			public const int ClearButton = 2131165232;
			
			// aapt resource value: 0x7f070012
			public const int DeleteButton = 2131165202;
			
			// aapt resource value: 0x7f07004a
			public const int DisplayCore = 2131165258;
			
			// aapt resource value: 0x7f07002a
			public const int EditButton = 2131165226;
			
			// aapt resource value: 0x7f070032
			public const int Error = 2131165234;
			
			// aapt resource value: 0x7f070018
			public const int FoodDisplay = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int FoodName = 2131165207;
			
			// aapt resource value: 0x7f07002c
			public const int GPSButton = 2131165228;
			
			// aapt resource value: 0x7f070025
			public const int ListButton = 2131165221;
			
			// aapt resource value: 0x7f07003e
			public const int ListingError = 2131165246;
			
			// aapt resource value: 0x7f070014
			public const int ListingSection = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int LogInError = 2131165210;
			
			// aapt resource value: 0x7f07002d
			public const int LogOutButton = 2131165229;
			
			// aapt resource value: 0x7f070020
			public const int Login = 2131165216;
			
			// aapt resource value: 0x7f07004b
			public const int NameDisplay = 2131165259;
			
			// aapt resource value: 0x7f070016
			public const int NameSection = 2131165206;
			
			// aapt resource value: 0x7f070022
			public const int NewUser = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int Password = 2131165215;
			
			// aapt resource value: 0x7f070027
			public const int RegionButton = 2131165223;
			
			// aapt resource value: 0x7f07004d
			public const int RegionDisplay = 2131165261;
			
			// aapt resource value: 0x7f070048
			public const int RegionName = 2131165256;
			
			// aapt resource value: 0x7f070005
			public const int SearchWine = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int SearchWineName = 2131165188;
			
			// aapt resource value: 0x7f070034
			public const int SignUpName = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int SignupPassword1 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int SignupPassword2 = 2131165238;
			
			// aapt resource value: 0x7f07003c
			public const int ThirdButton = 2131165244;
			
			// aapt resource value: 0x7f070026
			public const int TypeButton = 2131165222;
			
			// aapt resource value: 0x7f07004c
			public const int TypeDisplay = 2131165260;
			
			// aapt resource value: 0x7f070047
			public const int TypeName = 2131165255;
			
			// aapt resource value: 0x7f070011
			public const int UpdateButton = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int UpdateText = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int UserName = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int Vin_lyBanner = 2131165209;
			
			// aapt resource value: 0x7f070038
			public const int VinlyClear = 2131165240;
			
			// aapt resource value: 0x7f070024
			public const int VinlyLocale = 2131165220;
			
			// aapt resource value: 0x7f07001b
			public const int VinlyLogIn = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int VinlyLogIn2 = 2131165213;
			
			// aapt resource value: 0x7f070039
			public const int VinlyReturn = 2131165241;
			
			// aapt resource value: 0x7f070037
			public const int VinlySignup = 2131165239;
			
			// aapt resource value: 0x7f070023
			public const int VinlyUser = 2131165219;
			
			// aapt resource value: 0x7f070043
			public const int WineCommentNames = 2131165251;
			
			// aapt resource value: 0x7f070001
			public const int WineError = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int WineHunt = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int WineInstructions = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int WineList = 2131165205;
			
			// aapt resource value: 0x7f070040
			public const int WineName = 2131165248;
			
			// aapt resource value: 0x7f070046
			public const int WineRegion = 2131165254;
			
			// aapt resource value: 0x7f070042
			public const int WineRegionNames = 2131165250;
			
			// aapt resource value: 0x7f070045
			public const int WineType = 2131165253;
			
			// aapt resource value: 0x7f070041
			public const int WineTypeName = 2131165249;
			
			// aapt resource value: 0x7f070006
			public const int WineYear = 2131165190;
			
			// aapt resource value: 0x7f070049
			public const int YeaName = 2131165257;
			
			// aapt resource value: 0x7f070028
			public const int YearButton = 2131165224;
			
			// aapt resource value: 0x7f07004e
			public const int YearDisplay = 2131165262;
			
			// aapt resource value: 0x7f07000f
			public const int YearText = 2131165199;
			
			// aapt resource value: 0x7f07003b
			public const int addyText = 2131165243;
			
			// aapt resource value: 0x7f07002f
			public const int commentText = 2131165231;
			
			// aapt resource value: 0x7f07000d
			public const int editRegion = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int editType = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int editWine = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int editYear = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int findWine = 2131165191;
			
			// aapt resource value: 0x7f07002b
			public const int getPairing = 2131165227;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07003f
			public const int linearLayout2 = 2131165247;
			
			// aapt resource value: 0x7f070044
			public const int linearLayout3 = 2131165252;
			
			// aapt resource value: 0x7f07003d
			public const int linearLayout4 = 2131165245;
			
			// aapt resource value: 0x7f07003a
			public const int locText = 2131165242;
			
			// aapt resource value: 0x7f07001e
			public const int textView2 = 2131165214;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFood = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditWine = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GetFood = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PostWine = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignUp = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int VinGPS = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int WineList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WineName = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WineRegion = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int WineType = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int WineYear = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
